#!/usr/bin/env python
# -*- coding: utf-8 -*-


import argparse
import logging
import os
import sys

from git_deploy import commands


log = logging.getLogger(os.path.basename(__file__))


def main():
    parser = argparse.ArgumentParser(description=u'Deploy git repository changes to targets.')
    parser.add_argument('--config-file', default='~/.gitdeploy.json', help=u'Path of the config file')
    parser.add_argument('--origin-remote-name', default='origin', help=u'Name of the main remote repository')
    parser.add_argument('-v', '--verbose', action='store_true', default=False, help=u'Display info messages')
    subparsers = parser.add_subparsers(title=u'commands')
    pull_parser = subparsers.add_parser(u'pull')
    pull_parser.add_argument('targets', nargs='+', help=u'targets (relative to current repository)')
    pull_parser.add_argument('-n', '--dry-run', action='store_true', default=False, help=u'Do not execute actions')
    pull_parser.set_defaults(command=u'pull')
    push_parser = subparsers.add_parser(u'push')
    push_parser.add_argument('targets', nargs='+', help=u'targets (relative to current repository)')
    push_parser.add_argument('-n', '--dry-run', action='store_true', default=False, help=u'Do not execute actions')
    push_parser.set_defaults(command=u'push')
    targets_parser = subparsers.add_parser(u'targets')
    targets_parser.set_defaults(command=u'targets')
    args = parser.parse_args()
    logging.basicConfig(
        format=logging.BASIC_FORMAT if args.verbose else '%(message)s',
        level=logging.DEBUG if args.verbose else logging.INFO,
        )
    return commands.run_command(args)


if __name__ == '__main__':
    sys.exit(main())
